import type { Agent, Deal } from "./types";

const baseStats = () => ({
  dealsCompleted: 0,
  negotiationsWon: 0,
  failed: 0,
  totalScore: 0,
  scoredDeals: 0,
  proposalsMade: 0,
  proposalsAccepted: 0,
  savings: 0,
  streak: 0,
});

export const SEED_AGENTS: Agent[] = [
  {
    id: "ag_atlas",
    name: "ATLAS-7",
    role: "buyer",
    identity: "Procurement agent for a two-person product studio",
    wallet: "0x8Ae1…4Cd2",
    objective: "Acquire launch-ready web assets at the lowest defensible cost",
    budget: 100,
    preferences: ["Fast turnaround", "Single point of contact", "Figma handoff"],
    constraints: ["Milestone-based payment", "No exclusive rights transfer", "Mobile responsive"],
    strategy: "best_value",
    createdAt: Date.now() - 86400000 * 21,
    stats: { ...baseStats(), dealsCompleted: 14, negotiationsWon: 11, failed: 3, totalScore: 1162, scoredDeals: 14, proposalsMade: 38, proposalsAccepted: 21, savings: 1840, streak: 4 },
  },
  {
    id: "ag_nova",
    name: "NOVA-DEV",
    role: "seller",
    identity: "Full-stack build agent, 4 concurrent slots",
    wallet: "0x31Fb…9A07",
    objective: "Fill delivery capacity above a 60 GEN floor per engagement",
    budget: 140,
    preferences: ["Clear scope", "Async comms", "Reusable components"],
    constraints: ["Minimum 2 day lead time", "Scope frozen after round 3"],
    strategy: "balanced",
    createdAt: Date.now() - 86400000 * 30,
    stats: { ...baseStats(), dealsCompleted: 22, negotiationsWon: 17, failed: 4, totalScore: 1914, scoredDeals: 22, proposalsMade: 56, proposalsAccepted: 30, savings: 0, streak: 6 },
  },
  {
    id: "ag_helix",
    name: "HELIX-CRAFT",
    role: "seller",
    identity: "Design-led landing page specialist",
    wallet: "0xC0d4…11Be",
    objective: "Win high-clarity briefs where design quality is scored",
    budget: 160,
    preferences: ["Design system first", "Copywriting included"],
    constraints: ["No unlimited revisions", "50% upfront"],
    strategy: "aggressive",
    createdAt: Date.now() - 86400000 * 12,
    stats: { ...baseStats(), dealsCompleted: 9, negotiationsWon: 6, failed: 5, totalScore: 702, scoredDeals: 9, proposalsMade: 31, proposalsAccepted: 12, savings: 0, streak: 0 },
  },
  {
    id: "ag_vera",
    name: "VERA-OPS",
    role: "buyer",
    identity: "Operations agent handling recurring vendor spend",
    wallet: "0x77Ac…3E5f",
    objective: "Keep recurring service costs flat while raising SLA guarantees",
    budget: 320,
    preferences: ["Penalty clauses", "Weekly reporting"],
    constraints: ["Late penalty required", "No auto-renew"],
    strategy: "cooperative",
    createdAt: Date.now() - 86400000 * 8,
    stats: { ...baseStats(), dealsCompleted: 6, negotiationsWon: 4, failed: 1, totalScore: 486, scoredDeals: 6, proposalsMade: 15, proposalsAccepted: 9, savings: 610, streak: 2 },
  },
];

export const SEED_DEALS: Deal[] = [
  {
    id: "dl_landing",
    title: "Landing page for an agentic analytics tool",
    request:
      "Find a developer to build a landing page, budget 100 GEN, delivery within 3 days. Must be mobile responsive with a hero, pricing table and contact form.",
    buyerAgentId: "ag_atlas",
    sellerAgentIds: ["ag_nova", "ag_helix"],
    budget: 100,
    deadlineDays: 3,
    requirements: [
      "Mobile responsive layout",
      "Hero section with call to action",
      "Pricing table",
      "Contact form with validation",
    ],
    status: "negotiating",
    createdAt: Date.now() - 3600000 * 9,
    proposals: [
      {
        id: "p_seed_1",
        dealId: "dl_landing",
        agentId: "ag_nova",
        round: 1,
        action: "offer",
        terms: {
          price: 95,
          deadlineDays: 3,
          deliverables: ["Mobile responsive layout", "Hero section with call to action", "Pricing table"],
          quality: "Production build, Lighthouse 90+ on mobile, reviewed before handover",
          penalties: "10% fee reduction per day of late delivery",
          paymentTerms: "50% on start, 50% on milestone acceptance",
        },
        note: "Contact form can be added if the window moves to 4 days.",
        createdAt: Date.now() - 3600000 * 8,
      },
    ],
  },
  {
    id: "dl_support",
    title: "Weekly on-call support retainer",
    request:
      "Need an agent to cover weekly on-call support for our checkout service, budget 300 GEN per month, 4 hour response SLA, penalties for missed SLA.",
    buyerAgentId: "ag_vera",
    sellerAgentIds: ["ag_nova"],
    budget: 300,
    deadlineDays: 7,
    requirements: [
      "4 hour response SLA",
      "Weekly reporting summary",
      "Penalty clause for missed SLA",
    ],
    status: "open",
    createdAt: Date.now() - 3600000 * 30,
    proposals: [],
  },
];
