/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractRouteImport } from './routes/contract'
import { Route as FinderRouteImport } from './routes/finder'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as NegotiationsDealIdRouteImport } from './routes/negotiations.$dealId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractRoute = ContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const FinderRoute = FinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const NegotiationsDealIdRoute = NegotiationsDealIdRouteImport.update({
  id: '/negotiations/$dealId',
  path: '/negotiations/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/finder': typeof FinderRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/negotiations/$dealId': typeof NegotiationsDealIdRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/finder': typeof FinderRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/negotiations/$dealId': typeof NegotiationsDealIdRoute
  '/agents': typeof AgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/finder': typeof FinderRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/negotiations/$dealId': typeof NegotiationsDealIdRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contract'
    | '/finder'
    | '/leaderboard'
    | '/marketplace'
    | '/agents/$agentId'
    | '/negotiations/$dealId'
    | '/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contract'
    | '/finder'
    | '/leaderboard'
    | '/marketplace'
    | '/agents/$agentId'
    | '/negotiations/$dealId'
    | '/agents'
  id:
    | '__root__'
    | '/'
    | '/contract'
    | '/finder'
    | '/leaderboard'
    | '/marketplace'
    | '/agents/$agentId'
    | '/negotiations/$dealId'
    | '/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractRoute: typeof ContractRoute
  FinderRoute: typeof FinderRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MarketplaceRoute: typeof MarketplaceRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  NegotiationsDealIdRoute: typeof NegotiationsDealIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract': {
      id: '/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof ContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finder': {
      id: '/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof FinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiations/$dealId': {
      id: '/negotiations/$dealId'
      path: '/negotiations/$dealId'
      fullPath: '/negotiations/$dealId'
      preLoaderRoute: typeof NegotiationsDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractRoute: ContractRoute,
  FinderRoute: FinderRoute,
  LeaderboardRoute: LeaderboardRoute,
  MarketplaceRoute: MarketplaceRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  NegotiationsDealIdRoute: NegotiationsDealIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
